# Generated by Django 5.2.7 on 2025-10-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_last_name_service_tool_name_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/services/audio/'),
        ),
    ]
