# Generated by Django 5.2.7 on 2025-10-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_price_service_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='demo',
        ),
        migrations.AddField(
            model_name='template',
            name='demo_video',
            field=models.FileField(blank=True, help_text='Demo video file', null=True, upload_to='media/templates/demos/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, help_text='Template file', null=True, upload_to='media/templates/files/'),
        ),
    ]
