# Generated by Django 5.2.7 on 2025-10-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_template_demo_template_demo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.collaborator'),
        ),
    ]
