# Generated by Django 5.2.7 on 2025-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='livrable',
            name='is_reviewed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
