# Generated by Django 5.2.7 on 2025-10-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_livrable_is_reviewed_by_admin'),
    ]

    operations = [
        # First, remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        # Add the new fields
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.client'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Remove the old field
        migrations.RemoveField(
            model_name='review',
            name='livrable',
        ),
        # Finally, add the new unique_together constraint
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order', 'client')},
        ),
    ]
