# Generated by Django 5.2.7 on 2025-10-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_review_model'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the existing foreign key constraint
            "ALTER TABLE notifications DROP FOREIGN KEY notifications_order_id_2e72753f_fk_orders_id;",
            # Reverse operation (recreate the old constraint)
            "ALTER TABLE notifications ADD CONSTRAINT notifications_order_id_2e72753f_fk_orders_id FOREIGN KEY (order_id) REFERENCES orders (id);"
        ),
        migrations.RunSQL(
            # Add the new foreign key constraint with CASCADE delete
            "ALTER TABLE notifications ADD CONSTRAINT notifications_order_id_2e72753f_fk_orders_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;",
            # Reverse operation (drop the CASCADE constraint)
            "ALTER TABLE notifications DROP FOREIGN KEY notifications_order_id_2e72753f_fk_orders_id;"
        ),
    ]
