# Generated by Django 5.2.7 on 2025-10-22 09:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='blacklist_reason',
            field=models.TextField(blank=True, help_text='Reason for blacklisting (required if is_blacklisted is True)'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of commission applied to this order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission value applied to this order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='Mark this order as blacklisted'),
        ),
        migrations.AddField(
            model_name='order',
            name='sademy_commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated Sademy commission amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of commission calculation', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Commission value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_commission_enabled', models.BooleanField(default=True, help_text='Enable/disable automatic commission calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
                'db_table': 'global_settings',
            },
        ),
    ]
