# Generated by Django 5.2.7 on 2025-10-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_commission_and_blacklist_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='file_audio',
            field=models.FileField(blank=True, help_text='Audio file for the service', null=True, upload_to='media/'),
        ),
    ]
