# Generated by Django 5.2.7 on 2025-10-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_file_audio_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='Mark this client as blacklisted'),
        ),
    ]
