# Generated by Django 5.2.7 on 2025-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_client_blacklist_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='demo_video',
            field=models.FileField(blank=True, help_text='Demo video file', null=True, upload_to='templates/demos/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, help_text='Template file', null=True, upload_to='templates/files/'),
        ),
    ]
