# Generated by Django 5.2.7 on 2025-10-23 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_template_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the service was created'),
            preserve_default=False,
        ),
    ]
