# Generated by Django 5.2.7 on 2025-10-24 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_created_date_to_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_assigned', 'Order Assigned'), ('order_status_changed', 'Order Status Changed'), ('order_cancelled', 'Order Cancelled'), ('livrable_uploaded', 'Deliverable Uploaded'), ('livrable_reviewed', 'Deliverable Reviewed'), ('livrable_accepted', 'Deliverable Accepted'), ('livrable_rejected', 'Deliverable Rejected'), ('payment_reminder', 'Payment Reminder'), ('deadline_reminder', 'Deadline Reminder'), ('order_completed', 'Order Completed'), ('review_reminder', 'Review Reminder'), ('system_alert', 'System Alert'), ('account_created', 'Account Created'), ('user_blacklisted', 'User Blacklisted')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Notification priority level', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('is_email_sent', models.BooleanField(default=False, help_text='Whether email notification was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('livrable', models.ForeignKey(blank=True, help_text='Related deliverable (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.livrable')),
                ('order', models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.order')),
                ('user', models.ForeignKey(help_text='User who will receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
