# Generated by Django 5.2.7 on 2025-10-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Language code (e.g., 'en', 'fr', 'ar')", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Language name (e.g., 'English', 'French', 'Arabic')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is available for selection')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='Project description from chatbot or custom input'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_assigned', 'Order Assigned'), ('order_status_changed', 'Order Status Changed'), ('order_cancelled', 'Order Cancelled'), ('livrable_uploaded', 'Deliverable Uploaded'), ('livrable_reviewed', 'Deliverable Reviewed'), ('livrable_accepted', 'Deliverable Accepted'), ('livrable_rejected', 'Deliverable Rejected'), ('payment_reminder', 'Payment Reminder'), ('deadline_reminder', 'Deadline Reminder'), ('order_completed', 'Order Completed'), ('review_reminder', 'Review Reminder'), ('system_alert', 'System Alert'), ('account_created', 'Account Created'), ('user_blacklisted', 'User Blacklisted'), ('chatbot_order_created', 'Chatbot Order Created')], help_text='Type of notification', max_length=50),
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('custom_description', models.TextField(blank=True, help_text='Custom project description provided by the user')),
                ('client_name', models.CharField(blank=True, help_text="Client's name", max_length=200)),
                ('client_email', models.EmailField(blank=True, help_text="Client's email", max_length=254)),
                ('client_phone', models.CharField(blank=True, help_text="Client's phone number", max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the chatbot flow is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_service', models.ForeignKey(blank=True, help_text='Service selected by the user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
                ('selected_template', models.ForeignKey(blank=True, help_text='Template selected by the user (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template')),
                ('language', models.ForeignKey(blank=True, help_text='Selected language for the session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
            ],
            options={
                'verbose_name': 'Chatbot Session',
                'verbose_name_plural': 'Chatbot Sessions',
                'db_table': 'chatbot_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='chatbot_session',
            field=models.ForeignKey(blank=True, help_text='Chatbot session that created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.chatbotsession'),
        ),
    ]
