# Generated by Django 5.2.7 on 2025-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_language_order_description_and_more'),
    ]

    operations = [
        # These fields already exist in the database, we're just updating Django's state
        # We use RunSQL to handle the existing fields without trying to add them again
        migrations.RunSQL(
            "SELECT 1",  # No-op SQL since fields already exist
            reverse_sql="SELECT 1",
            state_operations=[
                migrations.AddField(
                    model_name='chatbotsession',
                    name='admin_notes',
                    field=models.TextField(blank=True, null=True, help_text='Admin notes about this session'),
                ),
                migrations.AddField(
                    model_name='chatbotsession',
                    name='chat_status',
                    field=models.CharField(blank=True, null=True, help_text='Current chat status', max_length=20),
                ),
                migrations.AddField(
                    model_name='chatbotsession',
                    name='conversation_history',
                    field=models.JSONField(default=list, help_text='Chat conversation history'),
                ),
                migrations.AddField(
                    model_name='chatbotsession',
                    name='whatsapp_link',
                    field=models.CharField(blank=True, null=True, help_text='WhatsApp link for the session', max_length=200),
                ),
            ]
        ),
    ]
