# Generated by Django 5.2.7 on 2025-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_update_chatbot_session_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Auto-generated order number (e.g., ORD-2024-0001)', max_length=20, null=True),
        ),
    ]
