# Generated by Django 5.2.7 on 2025-10-26 09:31

from django.db import migrations, models
from django.utils import timezone


def populate_order_numbers(apps, schema_editor):
    """Populate order numbers for existing orders"""
    Order = apps.get_model('core', 'Order')
    
    # Get all orders without order numbers (both NULL and empty string)
    orders = Order.objects.filter(
        models.Q(order_number__isnull=True) | models.Q(order_number='')
    ).order_by('date')
    
    current_year = timezone.now().year
    counter = 1
    
    for order in orders:
        # Generate order number
        order_number = f'ORD-{current_year}-{counter:04d}'
        order.order_number = order_number
        order.save(update_fields=['order_number'])
        counter += 1


def reverse_populate_order_numbers(apps, schema_editor):
    """Reverse migration - clear order numbers"""
    Order = apps.get_model('core', 'Order')
    Order.objects.update(order_number='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_order_number_field'),
    ]

    operations = [
        migrations.RunPython(populate_order_numbers, reverse_populate_order_numbers),
    ]
