# Generated by Django 5.2.7 on 2025-11-08 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


def populate_collaborator_commission(apps, schema_editor):
    GlobalSettings = apps.get_model('core', 'GlobalSettings')
    ServiceCollaboratorCommission = apps.get_model('core', 'ServiceCollaboratorCommission')
    Order = apps.get_model('core', 'Order')

    global_settings = GlobalSettings.objects.first()
    if global_settings is None:
        global_settings = GlobalSettings.objects.create(
            commission_type='percentage',
            commission_value=Decimal('20.00'),
            is_commission_enabled=True,
            collaborator_commission_type='percentage',
            collaborator_commission_value=Decimal('50.00'),
            is_collaborator_commission_enabled=True,
        )

    service_overrides = {
        override.service_id: override
        for override in ServiceCollaboratorCommission.objects.filter(is_active=True)
    }

    orders = Order.objects.select_related('service').all()
    for order in orders:
        commission_type = order.collaborator_commission_type
        commission_value = order.collaborator_commission_value

        if commission_value == Decimal('0.00'):
            override = service_overrides.get(order.service_id)
            if override:
                commission_type = override.commission_type
                commission_value = override.commission_value
            elif global_settings.is_collaborator_commission_enabled:
                commission_type = global_settings.collaborator_commission_type
                commission_value = global_settings.collaborator_commission_value

        if commission_type == 'percentage':
            payout = (order.total_price * commission_value) / Decimal('100.00')
        else:
            payout = commission_value

        order.collaborator_commission_type = commission_type
        order.collaborator_commission_value = commission_value
        order.collaborator_commission_amount = payout
        order.save(
            update_fields=[
                'collaborator_commission_type',
                'collaborator_commission_value',
                'collaborator_commission_amount',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_order_number_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='collaborator_commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of collaborator payout calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='collaborator_commission_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Collaborator payout value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='is_collaborator_commission_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable collaborator payout calculation'),
        ),
        migrations.AddField(
            model_name='order',
            name='collaborator_commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated collaborator payout amount for this order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='collaborator_commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of collaborator payout applied to this order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='collaborator_commission_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Collaborator payout value applied to this order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='ServiceCollaboratorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of collaborator payout calculation for this service', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, help_text='Collaborator payout value (percentage or fixed amount) for this service', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable/disable this service-specific collaborator payout configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_commission', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Collaborator Commission',
                'verbose_name_plural': 'Service Collaborator Commissions',
                'db_table': 'service_collaborator_commissions',
            },
        ),
        migrations.RunPython(populate_collaborator_commission, migrations.RunPython.noop),
    ]
