# Generated by Django 5.2.7 on 2025-11-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_order_number_unique_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['collaborator', 'status'], name='order_collab_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='order_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['service', 'status'], name='order_service_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'deadline_date'], name='order_status_deadline_idx'),
        ),
    ]
