"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv # Build paths inside the project like this: BASE_DIR / 'subdir'.
from urllib.parse import urlparse
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Secret Key
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# Debug Mode
DEBUG = config('DEBUG', default=True, cast=bool)

# Allowed Hosts
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <-- Must be first!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SlowRequestLoggingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js default dev server
    "http://127.0.0.1:3000",  # Alternative localhost
    "http://localhost:8000",  # Django dev server
    "http://127.0.0.1:8000",  # Alternative localhost for Django
    "https://sademy.ma",      # Production frontend
    "https://www.sademy.ma",  # Production frontend (www)
]

# Trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://sademy.ma",
    "https://www.sademy.ma",
]

# Allow credentials to be included in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow specific methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Expose headers to the client
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Parse MySQL URL if provided, otherwise use individual environment variables
mysql_url = config('MYSQL_URL', default='')
if mysql_url:
    # Parse MySQL URL: mysql://user:password@host:port/database
    parsed = urlparse(mysql_url)
    db_host = parsed.hostname if parsed.hostname else config('DB_HOST', default=None)
    db_port = str(parsed.port) if parsed.port else config('DB_PORT', default='3306')
    
    # If no host specified, try to detect from environment or use safe default
    if not db_host:
        # Check if we're in a containerized environment
        # Common indicators: Kubernetes, Docker, or other container platforms
        is_containerized = any([
            os.getenv('KUBERNETES_SERVICE_HOST'),
            os.getenv('DOCKER_HOST'),
            os.getenv('CONTAINER_ID'),
            os.path.exists('/.dockerenv'),
            os.path.exists('/.dockerinit'),
            (os.getenv('HOSTNAME') or '').startswith('k8s'),
            # Check if running in a container by examining common paths
            os.path.exists('/app') and os.path.exists('/app/.venv'),
        ])
        
        if is_containerized:
            # In containerized environments, default to common service names
            db_host = config('DB_HOST', default='mysql')  # Common service name
        else:
            # Local development - use 127.0.0.1 to force TCP/IP (not Unix socket)
            db_host = '127.0.0.1'
    
    # Force TCP/IP connection by converting 'localhost' to '127.0.0.1'
    # This prevents MySQLdb from trying to use Unix socket
    if db_host == 'localhost':
        db_host = '127.0.0.1'
    
    db_config = {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': parsed.path.lstrip('/') if parsed.path else config('DB_NAME', default='sademiy_db'),
        'USER': parsed.username if parsed.username else config('DB_USER', default='root'),
        'PASSWORD': parsed.password if parsed.password else config('DB_PASSWORD', default=''),
        'HOST': db_host,
        'PORT': db_port,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
else:
    # Fallback to individual environment variables
    db_host = config('DB_HOST', default=None)
    db_port = config('DB_PORT', default='3306')
    
    # If no host specified, try to detect from environment or use safe default
    if not db_host:
        # Check if we're in a containerized environment
        is_containerized = any([
            os.getenv('KUBERNETES_SERVICE_HOST'),
            os.getenv('DOCKER_HOST'),
            os.getenv('CONTAINER_ID'),
            os.path.exists('/.dockerenv'),
            os.path.exists('/.dockerinit'),
            (os.getenv('HOSTNAME') or '').startswith('k8s'),
            # Check if running in a container by examining common paths
            os.path.exists('/app') and os.path.exists('/app/.venv'),
        ])
        
        if is_containerized:
            # In containerized environments, default to common service names
            db_host = 'mysql'  # Common service name in Docker/Kubernetes
        else:
            # Local development - use 127.0.0.1 to force TCP/IP (not Unix socket)
            db_host = '127.0.0.1'
    
    # Force TCP/IP connection by converting 'localhost' to '127.0.0.1'
    # This prevents MySQLdb from trying to use Unix socket
    if db_host == 'localhost':
        db_host = '127.0.0.1'
    
    db_config = {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default='sademiy_db'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': db_host,
        'PORT': db_port,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }

DATABASES = {
    'default': db_config
}

# Keep database connections open for reuse and enable health checks
DATABASES['default']['CONN_MAX_AGE'] = 600
DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.DefaultPageNumberPagination',
    'PAGE_SIZE': 25,
}

# Email Configuration for Mailtrap
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='sandbox.smtp.mailtrap.io')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_FROM = config('EMAIL_FROM', default='noreply@sademiy.com')
DEFAULT_FROM_EMAIL = EMAIL_FROM

# Infobip Configuration for WhatsApp and SMS
INFOBIP_API_KEY = config('INFOBIP_API_KEY', default='')
INFOBIP_BASE_URL = config('INFOBIP_BASE_URL', default='https://api.infobip.com')
INFOBIP_SENDER = config('INFOBIP_SENDER', default='+212XXXXXXXXX')  # Format: +212XXXXXXXXX
INFOBIP_SMS_SENDER = config('INFOBIP_SMS_SENDER', default='447491163443')  # SMS sender number without +
ADMIN_PHONE = config('ADMIN_WHATSAPP_NUMBER', default='+212636359603')  # Admin phone for notifications

# Cache / Redis configuration
CACHE_URL = config('CACHE_URL', default='redis://127.0.0.1:6379/1')
CACHE_TTL = config('CACHE_TTL', default=300, cast=int)

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CACHE_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {'max_connections': 100},
        },
        'TIMEOUT': CACHE_TTL,
    }
}

# Celery configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 15  # 15 minutes
CELERY_BEAT_SCHEDULE = {}

# Logging configuration for slow queries and performance monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'performance': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

SLOW_REQUEST_THRESHOLD_MS = config('SLOW_REQUEST_THRESHOLD_MS', default=1000, cast=int)
SLOW_QUERY_THRESHOLD_MS = config('SLOW_QUERY_THRESHOLD_MS', default=500, cast=int)
ENABLE_QUERY_PROFILING = config('ENABLE_QUERY_PROFILING', default=False, cast=bool)
